language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0

before_install:
  - gem update bundler

notifications:
  email: false

gemfile:
  - gemfiles/padrino-0.11
  - gemfiles/padrino-0.12
  - gemfiles/padrino-0.13
